CREATE TABLE IF NOT EXISTS "Post" (
  id_post BIGSERIAL PRIMARY KEY,
  tytul TEXT NOT NULL,
  tresc TEXT NOT NULL,
  opublikowany BOOLEAN NOT NULL DEFAULT FALSE,
  utworzono TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
